name: Build Release

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:    
    uses: lumentae/actions/.github/workflows/build-cpp.yml@main
    with:
      vcpkg_packages: CLI11 spdlog CURL nlohmann-json libzippp hash-library
  release:
    permissions:
        contents: write
    needs: build
    uses: lumentae/actions/.github/workflows/release.yml@main
    with:
      commit-message: ${{ github.event.head_commit.message }}
    
