name: Build Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:    
    uses: lumentae/actions/.github/workflows/build-cpp.yml@main
    with:
      vcpkg_packages: CLI11 spdlog CURL nlohmann-json libzippp hash-library
    
